bulk indexing
BIBSYSDEV/nva-search-api pull request #113
Opened 2021-09-23 20:13 UTC by axthosarouris

2021-09-23 20:14 UTC, axthosarouris commented on batch-index/build.gradle
> +    implementation group: 'com.google.guava', name: 'guava', version: '30.1.1-jre'
for splitting a list into Lists

2021-09-23 20:15 UTC, axthosarouris commented on search-commons/src/main/java/no/unit/nva/search/ElasticSearchHighLevelRestClient.java
> +            .put(ELASTIC_SEARCH_INDEX_REFRESH_INTERVAL, FIFTEEN_MINUTES)
autoformating

2021-09-23 20:16 UTC, axthosarouris commented on search-commons/src/main/java/no/unit/nva/search/ElasticSearchHighLevelRestClient.java
> +    public List<BulkResponse> batchInsert(List<IndexDocument> indexDocuments) {
this is the main change. we break the list of index documents to bulks and send bulks for indexing

2021-09-23 20:17 UTC, axthosarouris commented on search-commons/src/main/java/no/unit/nva/search/ElasticSearchHighLevelRestClient.java
> +            .builder(HttpHost.create(ELASTICSEARCH_ENDPOINT_ADDRESS))
autoformating

2021-09-23 20:19 UTC, axthosarouris commented on search-commons/src/main/java/no/unit/nva/search/RestHighLevelClientWrapper.java
> +    public BulkResponse bulk(BulkRequest request, RequestOptions requestOption) throws IOException {
this class exists only to make the ElasticSearch client mockable. All methods in this class just call the respective EsClient method. In tests they are always mocked so they should be ignored by Jacoco

2021-09-24 04:08 UTC, brinxmat requested changes

2021-09-24 04:08 UTC, brinxmat commented on batch-index/src/main/java/no/unit/nva/search/BatchIndexer.java
> +        List<String> failures = collectFailures(result).collect(Collectors.toList());
I think it's a bit weird that the entire class simply returns a list of errors. For me, the IndexingResult class acts more like an interface for this class.

2021-09-24 04:08 UTC, brinxmat commented on batch-index/src/test/java/no/unit/nva/search/BatchIndexTest.java
>          "published_resources_identifiers_for_all_files.txt";
Remove unused vars

2021-09-24 04:08 UTC, brinxmat commented on batch-index/src/test/java/no/unit/nva/search/BatchIndexTest.java
> +    public static final int ARBITARY_QUERY_TIME = 123;
spelling

2021-09-24 04:08 UTC, brinxmat commented on batch-index/src/test/java/no/unit/nva/search/BatchIndexTest.java
> +    private Failure creteFailure(SortableIdentifier id) {
create

2021-09-24 04:08 UTC, brinxmat commented on batch-index/src/test/java/no/unit/nva/search/StubElasticSearchHighLevelRestClient.java
> +    public static final DocWriteResponse DOC_WRITE_RESPONSE = null;
Remove unused

2021-09-24 04:08 UTC, brinxmat commented on search-commons/src/test/java/no/unit/nva/search/ElasticsearchSigningHighLevelRestClientTest.java
> +        var publications = IntStream.range(0, 1256).boxed()
vars and typed mixing?

2021-09-27 08:26 UTC, brinxmat approved these changes

2021-09-27 08:26 UTC, merged