Added handler to search any index
BIBSYSDEV/nva-search-api pull request #167
Opened 2021-12-01 14:34 UTC by janbj

2021-12-06 09:05 UTC, janbj commented on docs/openapi.yaml
> +  /{index}/search:
Copy-pasted from other search method. At this point we have not specified what the contract should be.

2021-12-06 09:42 UTC, brinxmat commented on search-resources-api/src/main/java/no/unit/nva/search/SearchHandler.java
> +        SearchResponse searchResponse = searchClient.doSearch(query, indexName);
Have a feeling SearchClient::doSearch should have RequestInfo as its argument

2021-12-06 09:42 UTC, brinxmat commented on search-resources-api/src/test/java/no/unit/nva/search/SearchHandlerTest.java
> +public class SearchHandlerTest {
Do we actually need this test? I'd expect it to be covered by the handler test

2021-12-06 12:07 UTC, axthosarouris requested changes

2021-12-06 12:07 UTC, axthosarouris commented on search-commons/src/main/java/no/unit/nva/search/models/SearchResourcesResponse.java
> +        return requestUri.addQueryParameter(QUERY_PARAMETER, searchTerm).getUri();
```
   private static URI createIdWithQuery(URI requestUri, String searchTerm) {
        return new UriWrapper(requestUri).addQueryParameter(QUERY_PARAMETER, searchTerm).getUri();
    }
```

2021-12-06 12:07 UTC, axthosarouris commented on search-resources-api/src/main/java/no/unit/nva/search/RequestUtil.java
> +        return new UriWrapper(HTTPS, domainName).addChild(path);
do not return the UriWrapper. return the URI. The UriWrapper is actually a class containing the supplied URI. Creating a class is almost for free and we do not pay much for creating many UriWrappers when we need them. Better to exchange URIs and if we need to manipulate them we can use UriWrappers now or something else later.

2021-12-06 12:07 UTC, axthosarouris commented on search-resources-api/src/test/java/no/unit/nva/search/SearchResourcesApiHandlerTest.java
> +        assertEquals(HttpStatus.SC_OK, gatewayResponse.getStatusCode());
I prefer to use HttpUrlConnection codes instead of HttpStatus because then we depend on an apache library for no reason

2021-12-06 12:07 UTC, axthosarouris commented on search-resources-api/src/test/java/no/unit/nva/search/SearchResourcesApiHandlerTest.java
> +        assertEquals(HttpStatus.SC_OK, gatewayResponse.getStatusCode());
ditto

2021-12-06 12:07 UTC, axthosarouris commented on search-resources-api/src/test/java/no/unit/nva/search/SearchResourcesApiHandlerTest.java
> +        assertEquals(HttpStatus.SC_BAD_GATEWAY, gatewayResponse.getStatusCode());
ditto

2021-12-07 10:06 UTC, axthosarouris approved these changes

2021-12-07 12:32 UTC, merged