Added search and filtering on ticket search.
BIBSYSDEV/nva-search-api pull request #267
Opened 2023-04-03 07:15 UTC by EyobSikt

Added search and filtering on ticket search.

2023-04-03 16:05 UTC, sondrev requested changes
1. You need to modify openapi.yaml and add the new query parameter to GET /ticket 
2. You need a unit test to SearchTicketsHandlerTest that checks that given a query, some data should be returned.

2023-04-12 07:01 UTC, brinxmat requested changes

2023-04-12 07:01 UTC, brinxmat commented on search-resources-api/src/test/java/no/unit/nva/search/SearchTicketsHandlerTest.java
> +        SearchResponseDto actual = gatewayResponse.getBodyObject(SearchResponseDto.class);
var

2023-04-12 07:01 UTC, brinxmat commented on search-resources-api/src/test/java/no/unit/nva/search/SearchTicketsHandlerTest.java
> +        SearchResponseDto expected = objectMapperWithEmpty
var

2023-04-12 11:08 UTC, brinxmat approved these changes

2023-04-12 12:23 UTC, sondrev approved these changes

2023-04-13 06:05 UTC, merged