https://unit.atlassian.net/browse/NP-45260
BIBSYSDEV/nva-search-api pull request #312
Opened 2023-09-14 12:57 UTC by StigNorland

2023-09-27 12:39 UTC, sondrev requested changes

2023-09-27 12:39 UTC, sondrev commented on docs/openapi.yaml
> +        description: "Result category code, category codes are defined in the Cristin API documentation."
We shouldent redirect to a documentation that will be taken down when NVA replaced Cristin

2023-09-27 12:39 UTC, sondrev commented on docs/openapi.yaml
> +        description: "DOI name (e.g. doi=10.1000/123456)"
Is there a example field we can use instead of putting it in the description?

2023-09-27 12:39 UTC, sondrev commented on docs/openapi.yaml
> +        description: "'fields=all' gives a list of result objects with all available fields. If this parameter is omitted, a list of result summaries with fewer fields will be returned."
what other values do we support? We use schema type 'string' underneath but here it seems like a enum or boolean? We should document all posibilities if its a enum

2023-09-27 12:39 UTC, sondrev commented on docs/openapi.yaml
> +        description: "Two letter language code. Using the 'lang' parameter, this is no longer in use, and are ignored"
if its no longer in use why not just remove it?

2023-09-27 12:39 UTC, sondrev commented on docs/openapi.yaml
>            type: string
its not a string if theres only 2 valid values

2023-09-27 12:39 UTC, sondrev commented on docs/openapi.yaml
>            type: string
should this be number?

2023-10-06 12:23 UTC, ketilaa commented
@StigNorland Ping. Have a look at the feedback so you can fix, merge and finish the work.

2023-10-18 13:04 UTC, StigNorland commented on search-commons/src/main/java/no/unit/nva/search2/ResourceAwsClient.java
> +        var searchAfter = query.removeValue(SEARCH_AFTER);
search_after needs to be removed from normal URI and handeled on its own.

2023-10-18 13:14 UTC, merged