Np 46571/np 46883 accent
BIBSYSDEV/nva-search-api pull request #523
Opened 2024-06-07 09:01 UTC by StigNorland

2024-06-10 07:54 UTC, StigNorland commented on search-commons/src/test/java/no/unit/nva/search/OpensearchTest.java
Time to prune old code....
Removing Opensearchtest, as new changes break these tests, and all search code is now on search2.
More pruning in the pipeline.

2024-06-12 07:16 UTC, brinxmat requested changes

2024-06-12 07:16 UTC, brinxmat commented on indexing-handlers/src/main/java/no/unit/nva/indexing/model/IndexRequest.java
> +            .orElseThrow();
Had to do a double-take here as I imagined I was seeing double :D Can you extract the mapping + type reference to its own method `mapToJavaType(String jsonString)`

2024-06-12 08:07 UTC, brinxmat approved these changes

2024-06-12 08:07 UTC, merged