Add exclusion of incomplete records
BIBSYSDEV/nva-search-api pull request #9
Opened 2020-09-18 13:09 UTC by brinxmat

Excludes documents that would not be searchable (but are likely never sent for processing)
Fixes a number of issues, test coverage, URI management and JSON generation

2020-09-18 18:25 UTC, axthosarouris commented on search-resources-api/src/main/java/no/unit/nva/dynamodb/DynamoDBStreamHandler.java
> +        if (isNull(document)) {
cleaner if we write 

```
 private void upsertSearchIndex(DynamodbEvent.DynamodbStreamRecord streamRecord) throws SearchException {
        logStreamRecord(streamRecord);
        DynamoDBEventTransformer eventTransformer = new DynamoDBEventTransformer();
        var document = eventTransformer.parseStreamRecord(streamRecord);
        if (nonNull(document)) {
            elasticSearchClient.addDocumentToIndex(document);
        }
    }
```

2020-09-18 18:25 UTC, axthosarouris commented on search-resources-api/src/main/java/no/unit/nva/search/IndexDate.java
> +     * Constructor for basic serialization of IndexDate.
Constructor for basic **de**serilization ...

2020-09-18 18:25 UTC, axthosarouris commented on search-resources-api/src/test/java/no/unit/nva/dynamodb/DynamoDBStreamHandlerTest.java
> +        IndexDate date = new IndexDate("2020", "09", "08");
Refactor to a method with name bookEntryWithNoEmptyFields or sth like this.

2020-09-21 06:22 UTC, axthosarouris requested changes

2020-09-21 06:22 UTC, axthosarouris commented on search-resources-api/src/test/java/no/unit/nva/dynamodb/DynamoDBStreamHandlerTest.java
> +    void handlerReturnsSuccessMessageWhenDocumentDoesNotExist() throws IOException {
I think we should check that the ElasticSearch client is being called. You can use the Mockito expression verify for that

```
verify(restClient, (atLeastOnce()));
verify(restClient, (atMostOnce()));
verify(restClient, (times(1)));  
```

2020-09-21 06:22 UTC, axthosarouris commented on search-resources-api/src/test/java/no/unit/nva/dynamodb/DynamoDBStreamHandlerTest.java
> +    void handlerReturnsSuccessWhenEventNameIsValid(String eventName) throws IOException {
ditto

2020-09-21 06:22 UTC, axthosarouris commented on search-resources-api/src/test/java/no/unit/nva/search/SearchResourcesApiHandlerTest.java
> +        assertThrows(ApiGatewayException.class, executable);
Very generic test that can succeed for other reasons than that expected here. SearchException is thrown at the moment. Consider deleting the test if this case is covered elsewhere

2020-09-21 12:50 UTC, svenngjeto submitted a review, later dismissed

2020-09-23 10:26 UTC, svenngjeto submitted a review, later dismissed

2020-09-23 11:33 UTC, axthosarouris submitted a review, later dismissed

2020-09-23 15:30 UTC, brinxmat commented on search-resources-api/src/main/java/no/unit/nva/search/IndexDocument.java
> +        int lastPathElementSeparator = id.toString().lastIndexOf(PATH_SEPARATOR) + 1;
Added checking, we should fix this issue across the board in commons

2020-09-24 06:35 UTC, axthosarouris approved these changes

2020-09-24 07:13 UTC, merged